# app/Dockerfile

FROM python:3.11-slim-bookworm

WORKDIR /app

RUN apt-get update && apt-get install -y \
  curl \
  git \
  && rm -rf /var/lib/apt/lists/*


RUN git clone --depth 1 -b dev https://github.com/juancotrino/connecta-analytics.git . && \
  cd app/pages && \
  find . -maxdepth 1 -type f \
  ! -name 'Processing_Viewer.py' \
  ! -name '__init__.py' \
  -delete && \
  cd ../modules && \
  find . -maxdepth 1 -type f \
  ! -name 'authenticator.py' \
  ! -name 'styling.py' \
  ! -name 'preprocessing.py' \
  ! -name 'business_definition.py' \
  ! -name 'processing_viewer.py' \
  ! -name 'processing.py' \
  ! -name 'utils.py' \
  ! -name '__init__.py' \
  -delete

RUN pip install -r requirements.txt

ENV PORT=8080

EXPOSE ${PORT}

HEALTHCHECK CMD curl --fail http://localhost:${PORT}/_stcore/health

ENTRYPOINT ["sh", "-c", "exec streamlit run main.py --server.port=${PORT} --server.address=0.0.0.0"]
